name: Deploy (Self-Hosted Windows)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (monorepo)
        run: npm install

      - name: Deploy with Docker Compose (local machine)
        run: |
          docker compose up -d --build
          docker compose ps
          Write-Host "Frontend: http://localhost:8080"
          Write-Host "Backend:   http://localhost:3001/health"

